# Generated by Django 5.0.2 on 2024-02-27 04:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChargingAPI_Response', models.TextField()),
                ('StatusAPI_Response', models.TextField()),
                ('UnsubscribeAPI_Response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargingSDKs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APP_Name', models.CharField(max_length=255)),
                ('APP_ID', models.CharField(max_length=255)),
                ('API_Key', models.CharField(max_length=255)),
                ('API_Secret', models.CharField(max_length=255)),
                ('API_Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Contact must be a 13 digit number', regex='^\\d{13}$')])),
                ('redirect_url', models.URLField()),
                ('Subscriber_Name', models.CharField(max_length=255)),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='apiexecutor.chargingsdks')),
            ],
        ),
    ]
