# Generated by Django 5.0.2 on 2024-02-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiexecutor', '0004_subscriber_masked_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_response',
            name='request_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
